events {
    worker_connections 1024;
}

http {
    upstream monolith {
        server monolith:8000;
    }

    upstream auth {
        server auth-service:8001;
    }

    upstream messaging {
        server messaging-service:8002;
    }

    upstream presence {
        server presence-service:8003;
    }

    server {
        listen 8080;

        # Auth Service
        location /auth/ {
            proxy_pass http://auth;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Messaging Service
        location /messages/ {
            proxy_pass http://messaging/messages/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Presence Service
        location /presence/ {
            proxy_pass http://presence;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # WebSockets del monolito
        location /groups/ws/ {
            proxy_pass http://monolith/groups/ws/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        # WebSockets DM del monolito
        location /groups/dm/ws/ {
            proxy_pass http://monolith/groups/dm/ws/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        # Todo lo demás va al monolito
        location / {
            proxy_pass http://monolith/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}