apiVersion: apps/v1
kind: Deployment
metadata:
  name: presence-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presence-service
  template:
    metadata:
      labels:
        app: presence-service
    spec:
      containers:
      - name: presence-service
        image: groupsapp_d-presence-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-svc:9092"
        - name: SECRET_KEY
          value: "super-secret-key-change-in-production"
        - name: ALGORITHM
          value: "HS256"
        ports:
        - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: presence-service
spec:
  selector:
    app: presence-service
  ports:
  - port: 8003
    targetPort: 8003
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: presence-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: presence-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50